version: 2
updates:
  - package-ecosystem: gomod
    directories: [/, /tools]
    schedule:
      interval: weekly
    groups:
      gomod:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
